### ISSUE TITLE
Specify huggingface_hub version

### ISSUE THREAD

**Issue by lumirth** [mzbac/mlx-nougat#1]
Had some trouble getting this to work. Was able to figure out that the huggingface_hub version was at fault. Installed a version from vaguely around when this package was made(0.24.1) and now everything works fine. Thought I'd say it here in case you're interested in updating this or if anybody else encounters the same problem.

**Comment by mzbac** [comment]
Thanks for bringing this up, @lumirth. I'll double-check if it's possible to update the package to support the latest version of huggingface_hub, or if we need to lock the version in requirements.txt

**Comment by mzbac** [comment]
fixed by https://github.com/mzbac/mlx-nougat/issues/1
